image: node:6.11.5

# This folder is cached between builds
cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - npm run test

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - docs
  only:
  - master
